header = "/**\n * C bindings for candidateparser library.\n * https://github.com/dbrgn/candidateparser\n **/"
include_guard = "candidateparser_bindings_h"
language = "C"
braces = "SameLine"

[parse]
parse_deps = false

[fn]
args = "Vertical"
